### ISSUE TITLE
The test yielded incorrect results

### ISSUE THREAD

**Issue by jihchao** [danipaco0/SudokuDetector#1]
When I run `python grid_detector.py`, the obtained sudoku has 7 filled in the spots where there are no numbers, but it should be filled with 0.

demo result:
```
[[3 7 7 8 7 8 7 7 2]
 [2 7 8 7 3 7 8 7 4]
 [7 7 7 2 7 4 7 7 7]
 [8 7 9 7 7 7 8 7 8]
 [7 6 7 7 7 7 7 5 7]
 [7 7 2 7 7 7 4 7 9]
 [7 7 7 5 7 9 7 7 7]
 [9 7 4 7 8 7 7 7 5]
 [8 7 7 6 7 7 7 7 3]]
```

**Comment by danipaco0** [comment]
The version of the project you used didn't process properly the images for OCR (it didn't remove the border from each cell image if a number was present) and the model training didn't have enough data. With the new version, the empty cells are returned as 0 and the OCR should have a 96% accuracy.

**Comment by jihchao** [comment]
Thank you for your quick response. your new version uses GPU, which I will test with NVIDIA graphics cards in the future, maybe. 
Thanks again.

**Comment by danipaco0** [comment]
The GPU computation (used for experimentation only) is just for the Gaussian blur. If you don't want to use it, you can replace the Gaussian blur function in image preprocessing with cv.GaussianBlur(grayscale, (9,9), 0).

**Comment by jihchao** [comment]
> The GPU computation (used for experimentation only) is just for the Gaussian blur. If you don't want to use it, you can replace the Gaussian blur function in image preprocessing with cv.GaussianBlur(grayscale, (9,9), 0).

Thank you very much.  your project is excellent.  however, due to limited server resources (GPU 〒▽〒), we have finally decided to use the opencv::ml library to recognize images on the mobile side.

Learned a lot from your project, thanks again.
